name: Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Regenerate Poetry lock file
      run: |
        poetry lock

    - name: Install dependencies
      run: |
        poetry install --no-interaction
        poetry add flake8 black mypy --group dev

    - name: Lint with flake8
      run: |
        # Only lint our own code, exclude dependencies and virtual environment
        poetry run flake8 core doc_engineer.py tests --count --select=E9,F63,F7,F82 --show-source --statistics
        poetry run flake8 core doc_engineer.py tests --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

    - name: Check formatting with black
      run: |
        # Only check formatting on our own code
        poetry run black --check core doc_engineer.py tests

    - name: Type check with mypy
      run: |
        poetry run mypy --ignore-missing-imports core doc_engineer.py 